version: '3.7'
services:
  php:
    image: php:7.4.2-fpm-alpine3.11
    restart: always
    volumes:
      - '../php:/var/www/html'

  nginx:
    image: nginx:1.17.8-alpine
    restart: always
    volumes:
      - '../nginx/config/default.conf:/etc/nginx/conf.d/default.conf'
      - '../nginx/html:/usr/share/nginx/html'
    ports:
      - "80:80"
